src/Entity/Snakes.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SnakesRepository")
 * @Vich\Uploadable
 */
class Snakes
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FrenchName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LatinName;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="snakes_image", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @Vich\UploadableField(mapping="distribution_image", fileNameProperty="distribution")
     * @var File
     */
    private $distributionFile;


    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $taille;

    /**
     * @ORM\Column(type="text")
     */
    private $nourriture;

    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $distribution;

    /**
     * @ORM\Column(type="text")
     */
    private $habitat;

    /**
     * @ORM\Column(type="text")
     */
    private $comportement;

    /**
     * @ORM\Column(type="text")
     */
    private $reproduction;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFrenchName(): ?string
    {
        return $this->FrenchName;
    }

    public function setFrenchName(string $FrenchName): self
    {
        $this->FrenchName = $FrenchName;

        return $this;
    }

    public function getLatinName(): ?string
    {
        return $this->LatinName;
    }

    public function setLatinName(string $LatinName): self
    {
        $this->LatinName = $LatinName;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }
    
    public function setDescription(string $Description): self
    {
        $this->Description = $Description;
        
        return $this;
    }
    
    public function getImageFile()
    {
        return $this->imageFile;
    }
    
    public function setImageFile(File $image)
    {
        $this->imageFile = $image;
        
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }
    
    public function getDistributionFile()
    {
        return $this->distributionFile;
    }
    
    public function setDistributionFile(File $distribution)
    {
        $this->distributionFile = $distribution;
        
        if ($distribution) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }
    

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function getTaille(): ?string
    {
        return $this->taille;
    }

    public function setTaille(string $taille): self
    {
        $this->taille = $taille;

        return $this;
    }

    public function getNourriture(): ?string
    {
        return $this->nourriture;
    }

    public function setNourriture(string $nourriture): self
    {
        $this->nourriture = $nourriture;

        return $this;
    }

    public function getDistribution()
    {
        return $this->distribution;
    }

    public function setDistribution($distribution)
    {
        $this->distribution = $distribution;

        return $this;
    }

    public function getHabitat(): ?string
    {
        return $this->habitat;
    }

    public function setHabitat(string $habitat): self
    {
        $this->habitat = $habitat;

        return $this;
    }

    public function getComportement(): ?string
    {
        return $this->comportement;
    }

    public function setComportement(string $comportement): self
    {
        $this->comportement = $comportement;

        return $this;
    }

    public function getReproduction(): ?string
    {
        return $this->reproduction;
    }

    public function setReproduction(string $reproduction): self
    {
        $this->reproduction = $reproduction;

        return $this;
    }


}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Snakes;

/**
 * @Route("/")
 */
class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     */
    public function index()
    {
        $snakes = $this->getDoctrine()->getRepository(Snakes::class);


        return $this->render('home/index.html.twig', [
            'snakes' => $snakes->findAll(),
        ]);
    }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
<link rel="stylesheet" href="./css/style.css" />
{% endblock %}
{% block title %}NaturaClic{% endblock %}

{% block body %}

<!-- Titre du contenu -->
<div class="container-fluid">
    <div class="row">
        <div class="titre col-12 p-5">
            <h1>LES REPTILES DU MAROC</h1>
        </div>
    </div>
</div>

<div id="content" class="container-fluid">
    <div class="row">
        <div class="col-10 mx-auto my-auto">
            <p>En juin 2018, j'ai eu la chance d'aller au Maroc pour une semaine d'Herping avec l'association Atheris
                que je remercie encore énormément pour cette semaine extraordinaire.
                <br>
                L'Herping, pour les non-initiés, ça ne veut pas dire grand chose, en fait, c'est simplement un mot qui a
                été trouvé pour dire "d'aller chercher et observer les reptiles et amphibiens dans la nature".
                <br>
                Nous étions donc 7 passionnés venus au Maroc dans le but d'observer et photographier un maximum
                d'espèces différentes et nous n'avons vraiment pas été déçus.
                <br>
                Nous avons donc observé un total de 42 espèces de Reptiles et Amphibiens dont voici la liste :</p>
        </div>
    </div>
</div>

<div id="snakeList" class="container-fluid">
    <div class="row">
        <h3 class="col-12">Les Serpents
            <hr>
        </h3>
    </div>
    <div class="row">
        <div class="col-md-4">
            <ul>{% for snake in snakes %}
                <li>
                    <a href=""> {{snake.FrenchName}} - {{snake.LatinName}} </a>
                    <hr>
                </li>
                {% endfor %}
            </ul>
        </div>
        {# <div class="col-12 col-sm-6">
            <ul>{% for snake in snakes |slice(7, 13) %}
                <li>
                    <a href=""> {{snake.FrenchName}} - {{snake.LatinName}} </a>
                    <hr>
                </li>
                {% endfor %}
            </ul>
        </div> #}
    </div>
</div>

<!-- Fin de Titre du contenu -->
<div class="shadow-title">
    <div id="snake-content" class="container main-pad">
        {% for snake in snakes %}
        <div class="row snake-line">
            <div class="snake-img col-12 col-lg-4"
                style="background-image: url('{{asset('uploads/images/snakes/' ~ snake.image)}}');">
                <div class="overlay">
                    <h3>{{snake.LatinName}}</h3>
                    <a class="btn">Découvrir les serpents</a>
                </div>
            </div>
            <div class="snake-desc col-12 col-lg-8">
                <div class="info">
                    <div class="card-text">
                        {{snake.description|raw}}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



<!-- Caroussel de photos de différentes snakess -->
<div class="caroussel">
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Cerastes2.jpg" alt="Slide1">
                </div>
                <div class="carousel-item active">
                    <img class="d-block w-100" src="./img/Cerastes4.jpg" alt="Slide2">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Cerastes6.jpg" alt="Slide3">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Daboia.jpg" alt="Slide4">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Malpolon.jpg" alt="Slide5">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Natrix.jpg" alt="Slide6">
                </div>
                <div class="carousel-item ">
                    <img class="d-block w-100" src="./img/Ragherhis.jpg" alt="Slide7">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Sténodactylus.jpg" alt="Slide8">
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="./img/Telescopus.jpg" alt="Slide9">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<!-- Caroussel de photos de différentes snakess -->


{% endblock %}